CREATE SEQUENCE account_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE transaction_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE audit_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE; 