version: '3.8'

services:
  oracle-db:
    environment:
      - ORACLE_CHARACTERSET=AL32UTF8
      - ORACLE_EDITION=enterprise
      - INIT_SGA_SIZE=1024
      - INIT_PGA_SIZE=512
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'

  redis:
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  banking-app:
    image: openjdk:17-jdk-slim
    container_name: banking-test-app
    depends_on:
      - oracle-db
      - redis
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521:ORCLCDB
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=Oracle123
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - LOGGING_LEVEL_COM_BANKING=DEBUG
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,metrics,info
    volumes:
      - ./target/banking-app-1.0.0.jar:/app/banking-app.jar
    command: java -jar /app/banking-app.jar
    networks:
      - oracle-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  newman:
    image: postman/newman:latest
    container_name: banking-newman
    depends_on:
      - banking-app
    volumes:
      - ./postman:/etc/newman
      - ./results:/var/newman
    command: >
      run Banking-API-Collection.json
      --environment environment.json
      --reporters cli,html,json
      --reporter-html-export /var/newman/postman/newman-report.html
      --reporter-json-export /var/newman/postman/newman-results.json
      --timeout-request 30000
      --delay-request 1000
    networks:
      - oracle-network
    profiles:
      - testing

  jmeter:
    image: justb4/jmeter:5.6.2
    container_name: banking-jmeter
    depends_on:
      - banking-app
    volumes:
      - ./jmeter:/jmeter
      - ./results:/results
    command: >
      -n -t /jmeter/Banking-Stress-Test.jmx
      -Jbase.url=http://banking-app:8081
      -Jthread.count=50
      -Jramp.up=30
      -Jduration=300
      -l /results/jmeter/jmeter-results.jtl
      -e -o /results/html-reports/jmeter-report
    networks:
      - oracle-network
    profiles:
      - testing

networks:
  oracle-network:
    driver: bridge 