services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:19.19.0.0
    container_name: oracle-19c-db-banking
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle123
      - ORACLE_EDITION=enterprise
      - ORACLE_CHARACTERSET=AL32UTF8
      - ENABLE_ARCHIVELOG=true
    ports:
      - "1522:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./init-scripts:/opt/oracle/scripts/startup
      - ./setup-scripts:/opt/oracle/scripts/setup
    networks:
      - oracle-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 3G
          cpus: '1.5'
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -S system/Oracle123@ORCLPDB1"]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 10m

  redis:
    image: redis:7-alpine
    container_name: banking-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - oracle-network
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  oracle_data:
    driver: local
  redis_data:
    driver: local

networks:
  oracle-network:
    driver: bridge